apiVersion: v1
kind: Secret
metadata:
  name: postgres-auth-credentials
  namespace: galaxy-empire
type: Opaque
stringData:
  POSTGRES_DB: auth_db
  POSTGRES_USER: auth_user
  POSTGRES_PASSWORD: auth_pass
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-game-credentials
  namespace: galaxy-empire
type: Opaque
stringData:
  POSTGRES_DB: game_db
  POSTGRES_USER: game_user
  POSTGRES_PASSWORD: game_pass
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: galaxy-empire
type: Opaque
stringData:
  JWT_SECRET: default-secret-change-in-production-at-least-256-bits-long
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: galaxy-empire
type: Opaque
stringData:
  GF_SECURITY_ADMIN_PASSWORD: admin
