package com.galaxyempire.game.domain;

public enum BuildingType {
    METAL_MINE, CRYSTAL_MINE, GAS_MINE,
    SOLAR_PLANT, FUSION_REACTOR,
    METAL_STORAGE, CRYSTAL_STORAGE, GAS_STORAGE,
    ROBOT_FACTORY, SHIPYARD, RESEARCH_LAB,
    RADAR, ALLIANCE_DEPOT, NANITE_FACTORY,
    TERRAFORMER, SILO, MOON_BASE
}
