CREATE TABLE planet (
    id BIGSERIAL PRIMARY KEY,
    player_id BIGINT NOT NULL,
    name VARCHAR(64) NOT NULL,
    galaxy SMALLINT NOT NULL,
    system_id INTEGER NOT NULL,
    slot SMALLINT NOT NULL,
    temperature INTEGER NOT NULL DEFAULT 0,
    metal DOUBLE PRECISION NOT NULL DEFAULT 500,
    crystal DOUBLE PRECISION NOT NULL DEFAULT 500,
    gas DOUBLE PRECISION NOT NULL DEFAULT 500,
    energy DOUBLE PRECISION NOT NULL DEFAULT 0,
    last_updated TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(galaxy, system_id, slot)
);

CREATE INDEX idx_planet_player ON planet(player_id);
